
services:
  framework-benchmarks:
    build: 
      context: .
      target: production
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      # Mount results directory for benchmarking (optional)
      - ./benchmark-results:/app/benchmark-results
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Development version with full benchmarking capabilities
  framework-benchmarks-dev:
    build:
      context: .
      target: development  
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./benchmark-results:/app/benchmark-results
      - ./results:/app/results
    profiles: ["dev"]
    restart: unless-stopped